Improved Makefile

diff --git a/end-to-end-openapi-postgres-hummingbird/example-openapi/Makefile b/end-to-end-openapi-postgres-hummingbird/example-openapi/Makefile
--- a/end-to-end-openapi-postgres-hummingbird/example-openapi/Makefile
+++ b/end-to-end-openapi-postgres-hummingbird/example-openapi/Makefile
@@ -2,22 +2,39 @@
 #
 #   % make help
 
+# Derived values (don't change these).
+CURRENT_MAKEFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
+CURRENT_MAKEFILE_DIR := $(patsubst %/,%,$(dir $(CURRENT_MAKEFILE_PATH)))
+
 # The following values can be changed here, or passed on the command line.
 SWIFT_OPENAPI_GENERATOR_GIT_URL ?= https://github.com/apple/swift-openapi-generator
 SWIFT_OPENAPI_GENERATOR_GIT_TAG ?= 1.10.4
 SWIFT_OPENAPI_GENERATOR_CLONE_DIR ?= $(CURRENT_MAKEFILE_DIR)/.swift-openapi-generator
 SWIFT_OPENAPI_GENERATOR_BUILD_CONFIGURATION ?= debug
-OPENAPI_YAML_PATH ?= $(CURRENT_MAKEFILE_DIR)/openapi/openapi.yaml
+SWIFT_OPENAPI_GENERATOR_BIN := $(SWIFT_OPENAPI_GENERATOR_CLONE_DIR)/.build/$(SWIFT_OPENAPI_GENERATOR_BUILD_CONFIGURATION)/swift-openapi-generator
+
+# OpenAPI configuration
+OPENAPI_YAML_DIRECTORY ?= $(CURRENT_MAKEFILE_DIR)/openapi
+OPENAPI_YAML_PATH ?= $(OPENAPI_YAML_DIRECTORY)/openapi.yaml
 OPENAPI_GENERATOR_CONFIG_PATH ?= $(CURRENT_MAKEFILE_DIR)/openapi-generator-config.yaml
 OUTPUT_DIRECTORY ?= $(CURRENT_MAKEFILE_DIR)/Sources/ExampleOpenAPI/
 
-# Derived values (don't change these).
-CURRENT_MAKEFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
-CURRENT_MAKEFILE_DIR := $(patsubst %/,%,$(dir $(CURRENT_MAKEFILE_PATH)))
-SWIFT_OPENAPI_GENERATOR_BIN := $(SWIFT_OPENAPI_GENERATOR_CLONE_DIR)/.build/$(SWIFT_OPENAPI_GENERATOR_BUILD_CONFIGURATION)/swift-openapi-generator
+# Docker configuration
+DOCKER_PATH ?= $(CURRENT_MAKEFILE_DIR)/docker
+DOCKER_OPENAPI_PATH ?= $(DOCKER_PATH)/openapi
+DOCKER_OPENAPI_WWW_PATH ?= $(DOCKER_OPENAPI_PATH)/www
+
+# Swagger UI configuration
+SWAGGER_UI_URL ?= https://cdn.jsdelivr.net/npm/swagger-ui-dist
+SWAGGER_UI_VERSION ?= 5.31.0
+SWAGGER_UI_PATH ?= $(DOCKER_OPENAPI_WWW_PATH)/swagger-ui
+SWAGGER_UI_JS_PATH ?= $(SWAGGER_UI_PATH)/bundle.min.js
+SWAGGER_UI_CSS_PATH ?= $(SWAGGER_UI_PATH)/min.css
 
 # If no target is specified, display help
 .DEFAULT_GOAL := help
+
+.PHONY: help generate build clean clean-all dump docker yaml
 
 help:  # Display this help.
 	@-+echo "Run make with one of the following targets:"
@@ -35,7 +52,7 @@ help:  # Display this help.
 	@-+echo "  OPENAPI_GENERATOR_CONFIG_PATH (e.g. openapi-generator-config.yaml)"
 	@-+echo "  OUTPUT_DIRECTORY (e.g. Sources/ManualGeneratorInvocationClient/Generated)"
 
-run: yaml generate docker
+run: yaml generate swagger-ui
 
 generate: $(SWIFT_OPENAPI_GENERATOR_BIN) $(OPENAPI_YAML_PATH) $(OPENAPI_GENERATOR_CONFIG_PATH) $(OUTPUT_DIRECTORY)  # Generate the sources using swift-openapi-generator.
 	$< generate \
@@ -53,6 +70,10 @@ clean:  # Delete the output directory used for generated sources.
 clean-all: clean  # Clean everything, including the checkout of swift-openapi-generator.
 	@echo 'Delete checkout of swift-openapi-generator $(SWIFT_OPENAPI_GENERATOR_CLONE_DIR)? [y/N] ' && read ans && [ $${ans:-N} = y ] || (echo "Aborted"; exit 1)
 	rm -rf "$(SWIFT_OPENAPI_GENERATOR_CLONE_DIR)"
+	@echo 'Delete SwaggerUI directory $(SWAGGER_UI_PATH)? [y/N] ' && read ans && [ $${ans:-N} = y ] || (echo "Aborted"; exit 1)
+	rm -rf "$(SWAGGER_UI_PATH)"
+	@echo 'Delete OpenAPI YAML files directory $(OPENAPI_YAML_DIRECTORY)? [y/N] ' && read ans && [ $${ans:-N} = y ] || (echo "Aborted"; exit 1)
+	rm -rf "$(OPENAPI_YAML_DIRECTORY)"
 
 
 dump:  # Dump all derived values used by the Makefile.
@@ -66,6 +87,10 @@ dump:  # Dump all derived values used by the Makefile.
 	@echo "OPENAPI_YAML_PATH = $(OPENAPI_YAML_PATH)"
 	@echo "OPENAPI_GENERATOR_CONFIG_PATH = $(OPENAPI_GENERATOR_CONFIG_PATH)"
 	@echo "OUTPUT_DIRECTORY = $(OUTPUT_DIRECTORY)"
+	@echo "SWAGGER_UI_DIRECTORY = $(SWAGGER_UI_PATH)"
+
+yaml: $(OPENAPI_YAML_DIRECTORY)
+	@cd generator && swift run
 
 $(SWIFT_OPENAPI_GENERATOR_CLONE_DIR):
 	git \
@@ -83,13 +108,22 @@ $(SWIFT_OPENAPI_GENERATOR_BIN): $(SWIFT_OPENAPI_GENERATOR_CLONE_DIR)
 		--configuration "$(SWIFT_OPENAPI_GENERATOR_BUILD_CONFIGURATION)" \
 		--product swift-openapi-generator
 
+$(OPENAPI_YAML_DIRECTORY):
+	mkdir -p "$@"
+
 $(OUTPUT_DIRECTORY):
 	mkdir -p "$@"
 
-.PHONY: help generate build clean clean-all dump docker yaml
+$(SWAGGER_UI_PATH):
+	mkdir -p "$@"
 
-yaml:
-	@cd generator && swift run
+$(SWAGGER_UI_JS_PATH): $(SWAGGER_UI_PATH)
+	curl -fLs "${SWAGGER_UI_URL}@${SWAGGER_UI_VERSION}/swagger-ui-bundle.min.js" -o "${SWAGGER_UI_JS_PATH}"
 
-docker:
-	@./docker/api/scripts/bootstrap.sh
+$(SWAGGER_UI_CSS_PATH): $(SWAGGER_UI_PATH)
+	curl -fLs "${SWAGGER_UI_URL}@${SWAGGER_UI_VERSION}/swagger-ui.min.css" -o "${SWAGGER_UI_CSS_PATH}"
+
+swagger-ui: $(SWAGGER_UI_JS_PATH) $(SWAGGER_UI_CSS_PATH)
+
+docker: run
+	docker compose up --build openapi
